// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcqxzKusZ6VvnInylF8FqLBDGATX0kxI',
    appId: '1:1004839467532:web:d8593f70dadc853f410c29',
    messagingSenderId: '1004839467532',
    projectId: 'linkup-17745',
    authDomain: 'linkup-17745.firebaseapp.com',
    storageBucket: 'linkup-17745.firebasestorage.app',
    measurementId: 'G-8FY1YLXR9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmcHVavSbL2Q3wFZIkR7RLkx4x1j2cW0',
    appId: '1:1004839467532:android:a381359636ce4b98410c29',
    messagingSenderId: '1004839467532',
    projectId: 'linkup-17745',
    storageBucket: 'linkup-17745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPtLlwy0vM70sdYass6nCwKtNLcDse75c',
    appId: '1:1004839467532:ios:8a1cfdc7a75a0d67410c29',
    messagingSenderId: '1004839467532',
    projectId: 'linkup-17745',
    storageBucket: 'linkup-17745.firebasestorage.app',
    iosBundleId: 'com.linkup.linkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPtLlwy0vM70sdYass6nCwKtNLcDse75c',
    appId: '1:1004839467532:ios:8a1cfdc7a75a0d67410c29',
    messagingSenderId: '1004839467532',
    projectId: 'linkup-17745',
    storageBucket: 'linkup-17745.firebasestorage.app',
    iosBundleId: 'com.linkup.linkup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcqxzKusZ6VvnInylF8FqLBDGATX0kxI',
    appId: '1:1004839467532:web:3d155c7e5fb71336410c29',
    messagingSenderId: '1004839467532',
    projectId: 'linkup-17745',
    authDomain: 'linkup-17745.firebaseapp.com',
    storageBucket: 'linkup-17745.firebasestorage.app',
    measurementId: 'G-XEQNNWNHY4',
  );
}
